"""football table

Revision ID: 1244b7d0b033
Revises: 4c833328eaa4
Create Date: 2025-09-10 17:06:48.173732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1244b7d0b033'
down_revision = '4c833328eaa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_football_table')
    with op.batch_alter_table('football_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Team', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('MP', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('W', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('D', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('L', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('PTS', sa.Integer(), nullable=True))
        batch_op.drop_column('played')
        batch_op.drop_column('won')
        batch_op.drop_column('points')
        batch_op.drop_column('team_name')
        batch_op.drop_column('draw')
        batch_op.drop_column('lost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lost', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('draw', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('team_name', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('won', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('played', sa.INTEGER(), nullable=True))
        batch_op.drop_column('PTS')
        batch_op.drop_column('L')
        batch_op.drop_column('D')
        batch_op.drop_column('W')
        batch_op.drop_column('MP')
        batch_op.drop_column('Team')

    op.create_table('_alembic_tmp_football_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Team', sa.VARCHAR(length=150), nullable=False),
    sa.Column('MP', sa.INTEGER(), nullable=True),
    sa.Column('W', sa.INTEGER(), nullable=True),
    sa.Column('D', sa.INTEGER(), nullable=True),
    sa.Column('L', sa.INTEGER(), nullable=True),
    sa.Column('PTS', sa.INTEGER(), nullable=True),
    sa.Column('league', sa.VARCHAR(length=150), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
