"""Add image_credit to memorabilia_story

Revision ID: 17cdb15b2f72
Revises: 45ad870b61de
Create Date: 2025-07-26 12:46:08.200973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cdb15b2f72'
down_revision = '45ad870b61de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_credit', sa.String(length=100), nullable=True))
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('image_credit')

    # ### end Alembic commands ###
