"""add likes column in memorabilia and collector video

Revision ID: 27286a93a9d8
Revises: f2a9892f03be
Create Date: 2025-08-20 11:15:34.939372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27286a93a9d8'
down_revision = 'f2a9892f03be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collector_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('collector_video', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
