"""Add likes to memorabilia stories

Revision ID: 319d4a88721e
Revises: c6dfd35a7355
Create Date: 2025-08-16 15:12:59.480311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319d4a88721e'
down_revision = 'c6dfd35a7355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
