"""Add subscriber table

Revision ID: 392c4e762e05
Revises: a7c0052fe626
Create Date: 2025-07-22 10:50:21.786088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392c4e762e05'
down_revision = 'a7c0052fe626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('free_signup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('free_signup',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
