"""Add content field to MemorabiliaStory

Revision ID: 45ad870b61de
Revises: fdc1a25ac272
Create Date: 2025-07-26 11:49:17.979152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ad870b61de'
down_revision = 'fdc1a25ac272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.alter_column('subtitle',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.alter_column('subtitle',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('content')

    # ### end Alembic commands ###
