"""arenaplayadvertisement  migration

Revision ID: 45bd415d6703
Revises: 48fa93d1a04c
Create Date: 2025-09-20 10:28:31.101666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45bd415d6703'
down_revision = '48fa93d1a04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arenaplay_advertisement', schema=None) as batch_op:
        batch_op.drop_column('details')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arenaplay_advertisement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('details', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
