"""formula1 matchdetails migration

Revision ID: 48fa93d1a04c
Revises: 73bac3a37231
Create Date: 2025-09-17 10:13:44.637920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fa93d1a04c'
down_revision = '73bac3a37231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formula1_match_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('line1', sa.String(length=255), nullable=True),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('line3', sa.String(length=255), nullable=True),
    sa.Column('line4', sa.String(length=255), nullable=True),
    sa.Column('line5', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('match_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('line1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('line2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('line3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('line4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('line5', sa.VARCHAR(length=255), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('formula1_match_detail')
    # ### end Alembic commands ###
