"""football table

Revision ID: 4c833328eaa4
Revises: 9999484db489
Create Date: 2025-09-10 16:54:39.651171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c833328eaa4'
down_revision = '9999484db489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Team', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('MP', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('W', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('D', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('L', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('PTS', sa.Integer(), nullable=True))
        batch_op.drop_column('points')
        batch_op.drop_column('won')
        batch_op.drop_column('lost')
        batch_op.drop_column('draw')
        batch_op.drop_column('played')
        batch_op.drop_column('team_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('football_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('played', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('draw', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('lost', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('won', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('points', sa.INTEGER(), nullable=True))
        batch_op.drop_column('PTS')
        batch_op.drop_column('L')
        batch_op.drop_column('D')
        batch_op.drop_column('W')
        batch_op.drop_column('MP')
        batch_op.drop_column('Team')

    # ### end Alembic commands ###
