"""Add product title and fields

Revision ID: 6327e5634b97
Revises: 405ef3e13a49
Create Date: 2025-07-14 13:16:52.314609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6327e5634b97'
down_revision = '405ef3e13a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('link_url', sa.String(length=255), nullable=False))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('price')
        batch_op.drop_column('external_url')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('external_url', sa.VARCHAR(length=2083), nullable=False))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('link_url')
        batch_op.drop_column('image_url')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
