"""Initial migration

Revision ID: 633b08c8c7a6
Revises: 1244b7d0b033
Create Date: 2025-09-10 17:23:28.432959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633b08c8c7a6'
down_revision = '1244b7d0b033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_football_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_football_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Team', sa.VARCHAR(length=150), nullable=False),
    sa.Column('MP', sa.INTEGER(), nullable=True),
    sa.Column('W', sa.INTEGER(), nullable=True),
    sa.Column('D', sa.INTEGER(), nullable=True),
    sa.Column('L', sa.INTEGER(), nullable=True),
    sa.Column('PTS', sa.INTEGER(), nullable=True),
    sa.Column('league', sa.VARCHAR(length=150), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
