"""Add is_short field to YouTubeVideo

Revision ID: 6428b249099a
Revises: 6e47fb0f3a8e
Create Date: 2025-08-19 11:50:16.152970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6428b249099a'
down_revision = '6e47fb0f3a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('you_tube_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_short', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('you_tube_video', schema=None) as batch_op:
        batch_op.drop_column('is_short')

    # ### end Alembic commands ###
