"""Add likes to memorabilia

Revision ID: 6e47fb0f3a8e
Revises: 80ecdb5adfd9
Create Date: 2025-08-16 15:52:38.851413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e47fb0f3a8e'
down_revision = '80ecdb5adfd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.INTEGER(), nullable=True))

    op.create_table('like',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('story_id', sa.INTEGER(), nullable=False),
    sa.Column('user_identifier', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['memorabilia_story.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'user_identifier', name=op.f('unique_user_like'))
    )
    # ### end Alembic commands ###
