"""boxing and mma ranking  migration

Revision ID: 73bac3a37231
Revises: 633b08c8c7a6
Create Date: 2025-09-13 15:23:35.765761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bac3a37231'
down_revision = '633b08c8c7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mma_ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fighter_name', sa.String(length=150), nullable=False))
        batch_op.drop_column('boxer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mma_ranking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boxer_name', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('fighter_name')

    # ### end Alembic commands ###
