"""collectibles stories  migration

Revision ID: 7caa6f417d94
Revises: 45bd415d6703
Create Date: 2025-09-24 14:24:08.710426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7caa6f417d94'
down_revision = '45bd415d6703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collectible_story', schema=None) as batch_op:
        batch_op.drop_column('video_url')
        batch_op.drop_column('video_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collectible_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=512), nullable=True))

    # ### end Alembic commands ###
