"""Add likes to memorabilia stories

Revision ID: 80ce92c0b3b9
Revises: 319d4a88721e
Create Date: 2025-08-16 15:23:10.096944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ce92c0b3b9'
down_revision = '319d4a88721e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memorabilia_like')
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), nullable=True))

    op.create_table('memorabilia_like',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('story_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['memorabilia_story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'story_id', name=op.f('unique_like'))
    )
    # ### end Alembic commands ###
