"""Add likes to memorabilia

Revision ID: 80ecdb5adfd9
Revises: 80ce92c0b3b9
Create Date: 2025-08-16 15:50:27.034311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ecdb5adfd9'
down_revision = '80ce92c0b3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
