"""Add MemorabiliaStory

Revision ID: 90660dc5ea40
Revises: c20aca127c56
Create Date: 2025-07-25 12:20:15.375546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90660dc5ea40'
down_revision = 'c20aca127c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('link_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
