"""Add MemorabiliaStory

Revision ID: 990f0dc64c5d
Revises: 1e1d2b9b8009
Create Date: 2025-07-25 12:09:47.634124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990f0dc64c5d'
down_revision = '1e1d2b9b8009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
