"""Add likes column in both

Revision ID: 9999484db489
Revises: 8a60b04cbfbd
Create Date: 2025-08-20 12:05:25.699884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9999484db489'
down_revision = '8a60b04cbfbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collector_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('likes')

    with op.batch_alter_table('collector_video', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
