"""Add caption and credit to News

Revision ID: a7c0052fe626
Revises: 57d09fc2d068
Create Date: 2025-07-15 10:56:12.868805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c0052fe626'
down_revision = '57d09fc2d068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_caption', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_credit', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('image_credit')
        batch_op.drop_column('image_caption')

    # ### end Alembic commands ###
