"""Add MemorabiliaStory

Revision ID: c20aca127c56
Revises: 990f0dc64c5d
Create Date: 2025-07-25 12:18:05.818038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20aca127c56'
down_revision = '990f0dc64c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=50), nullable=True))
        batch_op.drop_column('time_posted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_posted', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
