"""Add video to MemorabiliaStory

Revision ID: c6dfd35a7355
Revises: 17cdb15b2f72
Create Date: 2025-08-11 10:50:55.985980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6dfd35a7355'
down_revision = '17cdb15b2f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.drop_column('video_url')
        batch_op.drop_column('video_filename')

    # ### end Alembic commands ###
