"""Add MemorabiliaStory

Revision ID: fdc1a25ac272
Revises: a2736018cee4
Create Date: 2025-07-26 11:13:47.166498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc1a25ac272'
down_revision = 'a2736018cee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.alter_column('subtitle',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorabilia_story', schema=None) as batch_op:
        batch_op.alter_column('subtitle',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
